version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: deps-{{ .Branch }}
          key: deps-
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm

      - run:
          name: test
          command: npm t
      - run:
          name: release
          command: npm run semantic-release || true
